### ISSUE TITLE
Testing failures with vala 0.46.1

### ISSUE THREAD

**Issue by worldofpeace** [vala-lang/vala-lint#133]
##### Description
What is says. With vala `0.46.1` the tests fail, along with some critical messages.
I did test with vala 0.40 and there wasn't any issues.
Can you perhaps test against newer vala in your CI?

##### Meson logs
```

(process:405): vala-CRITICAL **: 18:35:37.510: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.511: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.511: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.511: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.511: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.511: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.511: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.511: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.512: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.512: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.512: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.512: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.512: vala_source_reference_get_begin: assertion 'self != NULL' failed

(process:405): vala-CRITICAL **: 18:35:37.512: vala_source_reference_get_begin: assertion 'self != NULL' failed
-------

2/2 vala lint file test                     FAIL     0.27 s (killed by signal 6 SIGABRT)

--- command ---
build/test/file-test
--- stdout ---
Bail out! ERROR:test/9f86d08@@file-test@exe/FileTest.c:211:file_test_check_file_for_mistake: assertion failed: (mistakes[i].begin.line == mistake_list[i].line)
--- stderr ---
**
ERROR:test/9f86d08@@file-test@exe/FileTest.c:211:file_test_check_file_for_mistake: assertion failed: (mistakes[i].begin.line == mistake_list[i].line)
-------


Ok:                    1
Expected Fail:         0
Fail:                  1
Unexpected Pass:       0
Skipped:               0
Timeout:               0
```

##### Backtrace
```
Thread 3 (Thread 0x7fdedab4e700 (LWP 407)):
#0  0x00007fdeddd0b501 in poll () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6
#1  0x00007fdeddfe7f36 in g_main_context_iterate.isra () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#2  0x00007fdeddfe805c in g_main_context_iteration () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#3  0x00007fdeddfe80a1 in glib_worker_main () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#4  0x00007fdede0110fd in g_thread_proxy () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#5  0x00007fdeddb3aef7 in start_thread () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libpthread.so.0
#6  0x00007fdeddd1522f in clone () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6

Thread 2 (Thread 0x7fdeda34d700 (LWP 408)):
#0  0x00007fdeddd0b501 in poll () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6
#1  0x00007fdeddfe7f36 in g_main_context_iterate.isra () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#2  0x00007fdeddfe828a in g_main_loop_run () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#3  0x00007fdede2256b6 in gdbus_shared_thread_func () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libgio-2.0.so.0
#4  0x00007fdede0110fd in g_thread_proxy () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#5  0x00007fdeddb3aef7 in start_thread () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libpthread.so.0
#6  0x00007fdeddd1522f in clone () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6

Thread 1 (Thread 0x7fdedda3f880 (LWP 406)):
#0  0x00007fdeddc57be0 in raise () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6
#1  0x00007fdeddc58dc1 in abort () from /nix/store/6yaj6n8l925xxfbcd65gzqx3dz7idrnn-glibc-2.27/lib/libc.so.6
#2  0x00007fdeddfb4dc3 in g_assertion_message.cold () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#3  0x00007fdede01036a in g_assertion_message_expr () from /nix/store/s7rq6rzl851kv70s92zwrnbsw86rnkwj-glib-2.62.0/lib/libglib-2.0.so.0
#4  0x00000000004015fd in file_test_check_file_for_mistake (file=file@entry=0x893b20, mistake_list=mistake_list@entry=0x8c1f70) at test/9f86d08@@file-test@exe/FileTest.c:211
#5  0x000000000040205c in file_test_main (args=<optimized out>, args_length1=<optimized out>) at test/9f86d08@@file-test@exe/FileTest.c:436
#6  0x00000000004020be in main (argc=<optimized out>, argv=<optimized out>) at test/9f86d08@@file-test@exe/FileTest.c:448
```

**Comment by ricotz** [comment]
Would be nice to get this bisected, while 0.44.x doesn't show the issue, but 0.46.x and git master do.

**Comment by ricotz** [comment]
See https://github.com/vala-lang/vala-lint/pull/134
